title: Jarod Wright # 
logo: "/images/me.jpeg?raw=true" # photo 
description: > 

  <br><br>
  TEST asdlfhjasdlkfhjasdklfhasdklfjasdfkljandkfljnkajsdf
  asdfaskdjnfaskldjfnalskdjnfaslkdjfn
  Research, Projects, ++, works in progress
  <br><br>
  
  
  
theme: jekyll-theme-minimal

