title: Jarod Wright # 
logo: "/images/me.jpeg?raw=true" # photo 
description: > 
 I have worked as a Fraud Researcher and Data Analyst for the Montana Department of Labor and Industry approaching 2 years. 

  <br><br>
    In this role I have instituted new workflows, automated fraud detection tasks, and produced consistent reports and dashboards with a variety of tools.  
  <br><br>
 <a href="https://www.linkedin.com/in/jarod-wright-36a107211/">View My LinkedIn Profile</a>
  
  
  
theme: jekyll-theme-minimal

