title: Jarod Wright # your name (or website title) here
logo: "/images/me.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Research, Projects, ++, works in progress
  <br><br>
  
  <a href="https://github.com/jwUTC/Projects">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal

