title: Jarod Wright # 
logo: "/images/me.jpeg?raw=true" # photo 
description: > 
  Research, Projects, ++, works in progress
  <br><br>
  
  <a href="https://github.com/jwUTC/Projects">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal

