title: Jarod Wright # 
logo: "/images/me.jpeg?raw=true" # photo 
description: > 
 I have worked as a Fraud Researcher and Data Analyst for the Montana Deparartment of Labor and Industry approaching 2 years. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  Research, Projects, ++, works in progress
  <br><br>
  
  
  
theme: jekyll-theme-minimal

